### ISSUE TITLE
How to set background image like this?

### ISSUE THREAD

**Issue by zyf0330** [robertknight/konsole#1]
```
    - Usage can be either
      - "tile"   - the image is tilewise replicated.
      - "center" - the image is centered.
      - "full"   - the image is stretched to fit the window size.
```
I find doc in https://github.com/robertknight/konsole/blob/master/data/color-schemes/historic/README.Schema, but where is it in konsole profile settings?

**Comment by robertknight** [comment]
Hello. This is an old personal fork of Konsole, not the official repository. I don’t know the answer to your question. Please ask the current developers / community.

**Comment by zyf0330** [comment]
sorry， I mistake
